### ISSUE TITLE
Massive changes at commit `61e8390`

### ISSUE THREAD

**Issue by vv-monsalve** [rfuenzalida/Freeman#22] opened 2023-11-23 22:01 UTC
Hi @rfuenzalida 
After pulling the latest files at commit `61e8390` there are massive regressions for the font (from its previous state at commit `4a3e148`). Inspecting the commit history, some drastic changes are registered, like deleting the previous files.

Changes include terminal endings slope (`K, R, M, A, N, u`), spacing, and vertical metrics.

### Current `61e8390` Vs. `4a3e148`

![Freeman-diff-61e8390-glyphs](https://github.com/rfuenzalida/Freeman/assets/48698976/dbf81430-74c1-4888-a5da-8b52a468dcd7)

![Freeman-diff-61e8390](https://github.com/rfuenzalida/Freeman/assets/48698976/3d3b60db-42bd-4221-a5d0-75655643bbcb)

---

### Current paring the vertical metrics to appreciate better the glyphs changes

![Freeman-diff-61e8390-equalVM](https://github.com/rfuenzalida/Freeman/assets/48698976/40558c4b-b280-41ba-809b-0ba511042699)

Please review everything, and confirm if these changes are actually intended. If so, please provide some added information about them to better asses them within the development process.

**Comment by rfuenzalida** [comment] 2023-11-23 22:21
Hi @vv-monsalve Viviana, I can confirm that the changes on this latest commit are intended, the only change that seems to be an error on my side is the change of the vertical metrics but everything else is the latest version adding all the changes made by Summer of Type including the tighten spacing and the new Sterling.

**Comment by rfuenzalida** [comment] 2023-11-24 08:21
Since we're again on track and everything's clarified will close this issue.

**Closed by rfuenzalida** 2023-11-24 08:21 UTC
